project:
  type: website
  output-dir: docs

website:
  # title: "SmallCoder128.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - resume.qmd
    right: 
      - icon: github
        href: http://github.com/SmallCoder128

format:
  html:
    theme:
      light: flatly
      dark: solar 
    css: styles.css
    toc: true

editor: visual

